apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        hosts /etc/coredns/NodeHosts {
          ttl 60
          reload 15s
          fallthrough
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
        import /etc/coredns/custom/*.override
    }
    import /etc/coredns/custom/*.server
  NodeHosts: |
    172.20.0.1 host.k3d.internal
    172.20.0.2 k3d-iot-server-0
    172.20.0.3 k3d-iot-serverlb
kind: ConfigMap
metadata:
  annotations:
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/4yQT4vUQBDFv0pT56TNn5nN2OBB9iKIHj3tpZKubNr0VA1dtZFl2O8uYXARZNXba35dj/feFfCSvlHRJAwBthYqiGgI4Qr3UmhOmSCAD8feXR/YOeeoFCl60wthtuWmC2F8vsn1aaTCZKRuyk9qVHwWqOCrRPokagoB2qHzXeMb37pF1PzaR5/YqDDmB36lnVv7WCexWqlsVOrmFcJLBWviCAHuhef0+AUvUMGZDH9VQGYxtCSs+1PG7zSZkvmSxE9olskneZd2D6je5PKDqdSP2woB1l5/I1tbuc+J44ePMQr/04LxvM85SaHI+l/f9YLTfrNvWuuzGp334hlHyn8ttaAuEGCcqDv13fvTqW2HQ49Nf7rD8dg2czffDTQPh+7QTMdhN/0j3psBXn4GAAD//1NNMaE5AgAA
    objectset.rio.cattle.io/id: ""
    objectset.rio.cattle.io/owner-gvk: k3s.cattle.io/v1, Kind=Addon
    objectset.rio.cattle.io/owner-name: coredns
    objectset.rio.cattle.io/owner-namespace: kube-system
  creationTimestamp: "2025-02-15T21:23:40Z"
  labels:
    objectset.rio.cattle.io/hash: bce283298811743a0386ab510f2f67ef74240c57
  name: coredns
  namespace: kube-system
  resourceVersion: "699"
  uid: ddf88723-420f-4d7f-bd12-146d3c3fda84
